name: Pull Request Action

on:
  pull_request:
    branches: [ main ]

# env:
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build_and_test:
    name: Build and Test
    uses: ./.github/workflows/build_and_test.yml
    with:
      configuration: Debug

  # delete_artifact:
  #   name: Delete Artifact
  #   needs: [plan_terraform]
  #   runs-on: ubuntu-latest
  #   if: success() || failure() || cancelled()
  #   steps:
  #     - name: Delete zip
  #       uses: GeekyEggo/delete-artifact@v2.0.0
  #       with:
  #         name: |
  #           publish.zip
  #           scheduler.zip
  